STR_V = "STR_V"
STR_G = "STR_G"
STR_H = "STR_H"
STR_HCOT = "STR_HCOT"
STR_E_FJ_H = "STR_E_FJ_H"
STR_FALLBACK_V = "STR_FALLBACK_V"

ALL_STRATEGIES = {
    STR_V,
    STR_G,
    STR_H,
    STR_HCOT,
    STR_E_FJ_H,
    STR_FALLBACK_V,
}

R_INTENT_CITATION = "R_INTENT_CITATION"
R_INTENT_RELATION = "R_INTENT_RELATION"
R_INTENT_METRIC = "R_INTENT_METRIC"
R_NEED_EXTERNAL = "R_NEED_EXTERNAL"
R_PROFILE_RESTRICTED = "R_PROFILE_RESTRICTED"
R_TOOL_UNHEALTHY_FALLBACK = "R_TOOL_UNHEALTHY_FALLBACK"
R_USE_HYBRID_PIPELINE = "R_USE_HYBRID_PIPELINE"
R_USE_HYBRIDCOT_PIPELINE = "R_USE_HYBRIDCOT_PIPELINE"
